---
name: Run Unit Tests
on:
  push:
    branches:
      - "*"

env:
  PROGRAM_NAME: ftrace

jobs:
  check_coding_style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install coding style checker
        run: |
          curl https://raw.githubusercontent.com/Epitech/coding-style-checker/refs/heads/main/coding-style.sh -o coding-style.sh
          chmod +x coding-style.sh

      - name: Run coding style checker
        run: |
          ./coding-style.sh .
          if [ -s coding-style-reports.log ]; then
            echo "[❌] Coding style errors found!"
            cat coding-style-reports.log
            exit 84
          else
            echo "[✅] No coding style errors detected!"
          fi

  run-project:
    needs: check_coding_style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make gcc

      - name: Build project
        run: make && make re && make clean

      - name: Run the project
        run: ./$PROGRAM_NAME -help

      - name: Fclean the project
        run: make fclean

  run-unit-tests:
    needs: run-project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc-multilib libcriterion-dev gcovr

      - name: Run unit tests
        run: |
          make tests_run
          if [ $? -ne 0 ]; then
            echo "[❌] tests_run failed"
            exit 84
          else
            echo "[✅] tests_run passed"
          fi

      - name: Fclean the project
        run: make fclean
